# Generated by Django 6.0.5 on 2026-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='booking_token',
            field=models.CharField(default='91cded7984c744128e1263171bcb53d3', max_length=32, unique=True),
        ),
    ]
